name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Ensure this matches the version of Node.js required by your project

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: |
        npm test
        exit_status=$?  # Capture the exit status of the npm test command
        if [ $exit_status -ne 0 ]; then  # Check if the exit status indicates test failure
          echo "Tests failed. Exiting with status code $exit_status."
          exit $exit_status  # Exit the workflow with the same status code as the failed tests
        fi
